micronaut:
  server:
    cors:
      enabled: true
      configurations:
        web:
        all:
          allowedMethods:
            - OPTIONS
            - POST
  application:
    name: text_analyzer

netty:
  default:
    allocator:
      max-order: 3